<script setup lang="ts">
import VotePage from './components/VotePage.vue';
import type { VoteItem } from './types/vote';

const voteItems: VoteItem[] = [{ id: '1', voterName: 'Lily', status: 'affirmative' },
{ id: '2', voterName: 'Jhon', status: 'negative' },
{ id: '3', voterName: 'Jack', status: 'pending' },
{ id: '4', voterName: 'Louis', status: 'abstain' },
{ id: '5', voterName: 'Amy', status: 'affirmative' },
{ id: '6', voterName: 'Bob', status: 'negative' },
{ id: '7', voterName: 'Cindy', status: 'pending' },
{ id: '8', voterName: 'David', status: 'abstain' },
{ id: '9', voterName: 'Emma', status: 'affirmative' },
{ id: '10', voterName: 'Frank', status: 'negative' },
{ id: '11', voterName: 'Grace', status: 'pending' },
{ id: '12', voterName: 'Henry', status: 'abstain' },
{ id: '13', voterName: 'Ivy', status: 'affirmative' },
{ id: '14', voterName: 'Jacky', status: 'negative' },
{ id: '15', voterName: 'Katie', status: 'pending' },
{ id: '16', voterName: 'Leo', status: 'abstain' },
{ id: '17', voterName: 'Mia', status: 'affirmative' },
{ id: '18', voterName: 'Noah', status: 'negative' },
{ id: '19', voterName: 'Olivia', status: 'pending' },
{ id: '20', voterName: 'Paul', status: 'abstain' },
{ id: '21', voterName: 'Quinn', status: 'affirmative' },
{ id: '22', voterName: 'Ryan', status: 'negative' },
{ id: '23', voterName: 'Sara', status: 'pending' },
{ id: '24', voterName: 'Tom', status: 'abstain' },
{ id: '25', voterName: 'Ulysses', status: 'affirmative' },
{ id: '26', voterName: 'Violet', status: 'negative' },
{ id: '27', voterName: 'Will', status: 'pending' },
{ id: '28', voterName: 'Xavier', status: 'abstain' },
{ id: '29', voterName: 'Yvonne', status: 'affirmative' },
{ id: '30', voterName: 'Zach', status: 'negative' },
{ id: '31', voterName: 'Ada', status: 'pending' },
{ id: '32', voterName: 'Kyle', status: 'abstain' },
{ id: '33', voterName: 'Li', status: 'affirmative' },
{ id: '34', voterName: 'Dan', status: 'negative' },
{ id: '35', voterName: 'Ella', status: 'pending' },
{ id: '36', voterName: 'Fred', status: 'abstain' },
{ id: '37', voterName: 'Grace', status: 'affirmative' },
{ id: '38', voterName: 'Harry', status: 'negative' },
{ id: '39', voterName: 'Irene', status: 'pending' },
{ id: '40', voterName: 'Jack', status: 'abstain' },
{ id: '41', voterName: 'Kate', status: 'affirmative' },
{ id: '42', voterName: 'Peter', status: 'negative' },
{ id: '43', voterName: 'Leo', status: 'negative' },
{ id: '44', voterName: 'Maggie', status: 'pending' },
{ id: '45', voterName: 'Nick', status: 'abstain' },
{ id: '46', voterName: 'Olivia', status: 'affirmative' },
{ id: '47', voterName: 'Queen', status: 'pending' },
{ id: '48', voterName: 'Ryan', status: 'abstain' },
{ id: '49', voterName: 'Sam', status: 'affirmative' },
{ id: '50', voterName: 'Tara', status: 'negative' },
{ id: '51', voterName: 'Ulysses', status: 'pending' },
{ id: '52', voterName: 'Violet', status: 'abstain' },
{ id: '53', voterName: 'Will', status: 'affirmative' },
{ id: '54', voterName: 'Xavier', status: 'negative' },
{ id: '55', voterName: 'Yvonne', status: 'pending' },
{ id: '56', voterName: 'Zach', status: 'abstain' },
{ id: '57', voterName: 'Adam', status: 'affirmative' },
{ id: '58', voterName: 'Beth', status: 'negative' },
{ id: '59', voterName: 'Carl', status: 'pending' },
{ id: '60', voterName: 'Danny', status: 'abstain' },
{ id: '61', voterName: 'Eve', status: 'affirmative' },
{ id: '62', voterName: 'Frank', status: 'negative' },
{ id: '63', voterName: 'Grace', status: 'pending' },
{ id: '64', voterName: 'Henry', status: 'abstain' },
{ id: '65', voterName: 'Ivy', status: 'affirmative' },
{ id: '66', voterName: 'Jacky', status: 'negative' },
{ id: '67', voterName: 'Katie', status: 'pending' },
{ id: '68', voterName: 'Leo', status: 'abstain' },
{ id: '69', voterName: 'Mia', status: 'affirmative' },
{ id: '70', voterName: 'Noah', status: 'negative' },
{ id: '71', voterName: 'Olivia', status: 'pending' },
{ id: '72', voterName: 'Paul', status: 'abstain' },
{ id: '73', voterName: 'Quinn', status: 'affirmative' },
{ id: '74', voterName: 'Ryan', status: 'negative' },
{ id: '75', voterName: 'Sara', status: 'pending' },
{ id: '76', voterName: 'Tom', status: 'abstain' },
{ id: '77', voterName: 'Ulysses', status: 'affirmative' },
{ id: '78', voterName: 'Violet', status: 'negative' },
{ id: '79', voterName: 'Will', status: 'pending' },
{ id: '80', voterName: 'Xavier', status: 'abstain' },
{ id: '81', voterName: 'Yvonne', status: 'affirmative' },
{ id: '82', voterName: 'Zach', status: 'negative' },
{ id: '83', voterName: 'Ada', status: 'pending' },
{ id: '84', voterName: 'Ben', status: 'abstain' },
{ id: '85', voterName: 'Carla', status: 'affirmative' },
{ id: '86', voterName: 'Dan', status: 'negative' },
{ id: '87', voterName: 'Ella', status: 'pending' },
{ id: '88', voterName: 'Fred', status: 'abstain' },
{ id: '89', voterName: 'Grace', status: 'affirmative' },
{ id: '90', voterName: 'Harry', status: 'negative' },
{ id: '91', voterName: 'Irene', status: 'pending' },
{ id: '92', voterName: 'Jack', status: 'abstain' },
{ id: '93', voterName: 'Kate', status: 'affirmative' },
{ id: '94', voterName: 'Leo', status: 'negative' },
{ id: '95', voterName: 'Maggie', status: 'pending' },
{ id: '96', voterName: 'Nick', status: 'abstain' },
{ id: '97', voterName: 'Olivia', status: 'affirmative' },
{ id: '98', voterName: 'Peter', status: 'negative' },
{ id: '99', voterName: 'Queen', status: 'pending' },
{ id: '100', voterName: 'Ryan', status: 'abstain' },
// 以下可继续按类似格式添加更多，此处省略部分中间内容以节省篇幅
{ id: '201', voterName: 'Luna', status: 'affirmative' },
{ id: '202', voterName: 'Marcus', status: 'negative' },
{ id: '203', voterName: 'Natalie', status: 'pending' },
{ id: '204', voterName: 'Oliver', status: 'abstain' },
{ id: '205', voterName: 'Penny', status: 'affirmative' },
{ id: '206', voterName: 'Quinn', status: 'negative' },
{ id: '207', voterName: 'Rachel', status: 'pending' },
{ id: '208', voterName: 'Sam', status: 'abstain' },
{ id: '209', voterName: 'Tara', status: 'affirmative' },
{ id: '210', voterName: 'Ulysses', status: 'negative' },
{ id: '211', voterName: 'Violet', status: 'pending' },
{ id: '212', voterName: 'Will', status: 'abstain' },
{ id: '213', voterName: 'Xavier', status: 'affirmative' },
{ id: '214', voterName: 'Yvonne', status: 'negative' },
{ id: '215', voterName: 'Zach', status: 'pending' },
{ id: '216', voterName: 'Ada', status: 'abstain' },
{ id: '217', voterName: 'Ben', status: 'affirmative' },
{ id: '218', voterName: 'Carla', status: 'negative' },
{ id: '219', voterName: 'Dan', status: 'pending' },
{ id: '220', voterName: 'Ella', status: 'abstain' },
{ id: '221', voterName: 'Fred', status: 'affirmative' },
{ id: '222', voterName: 'Grace', status: 'negative' },
{ id: '223', voterName: 'Harry', status: 'pending' },
{ id: '224', voterName: 'Irene', status: 'abstain' },
{ id: '225', voterName: 'Jack', status: 'affirmative' },
{ id: '226', voterName: 'Kate', status: 'negative' },
{ id: '227', voterName: 'Leo', status: 'pending' },
{ id: '228', voterName: 'Maggie', status: 'abstain' },
{ id: '229', voterName: 'Nick', status: 'affirmative' },
{ id: '230', voterName: 'Olivia', status: 'negative' },
{ id: '231', voterName: 'Peter', status: 'pending' },
{ id: '232', voterName: 'Queen', status: 'abstain' },
{ id: '233', voterName: 'Ryan', status: 'affirmative' },
{ id: '234', voterName: 'Sara', status: 'negative' },
{ id: '235', voterName: 'Tom', status: 'pending' },
{ id: '236', voterName: 'Ulysses', status: 'abstain' },
{ id: '237', voterName: 'Violet', status: 'affirmative' },
{ id: '238', voterName: 'Will', status: 'negative' },
{ id: '239', voterName: 'Xavier', status: 'pending' },
{ id: '240', voterName: 'Yvonne', status: 'abstain' },
{ id: '241', voterName: 'Zach', status: 'affirmative' },
{ id: '242', voterName: 'Ada', status: 'negative' },
{ id: '243', voterName: 'Ben', status: 'pending' },
{ id: '244', voterName: 'Carla', status: 'abstain' },
{ id: '245', voterName: 'Dan', status: 'affirmative' },
{ id: '246', voterName: 'Ella', status: 'negative' },
{ id: '247', voterName: 'Fred', status: 'pending' },
{ id: '248', voterName: 'Grace', status: 'abstain' },
{ id: '249', voterName: 'Harry', status: 'affirmative' },
{ id: '250', voterName: 'Irene', status: 'negative' },
{ id: '251', voterName: 'Jack', status: 'pending' },
{ id: '252', voterName: 'Kate', status: 'abstain' },
{ id: '253', voterName: 'Leo', status: 'affirmative' },
{ id: '254', voterName: 'Maggie', status: 'negative' },
{ id: '255', voterName: 'Nick', status: 'pending' },
{ id: '256', voterName: 'Olivia', status: 'abstain' },
{ id: '257', voterName: 'Peter', status: 'affirmative' },
{ id: '258', voterName: 'Queen', status: 'negative' },
{ id: '259', voterName: 'Ryan', status: 'pending' },
{ id: '260', voterName: 'Sara', status: 'abstain' },
{ id: '261', voterName: 'Tom', status: 'affirmative' },
{ id: '262', voterName: 'Ulysses', status: 'negative' },
{ id: '263', voterName: 'Violet', status: 'pending' },
{ id: '264', voterName: 'Will', status: 'abstain' },
{ id: '265', voterName: 'Xavier', status: 'affirmative' },
{ id: '266', voterName: 'Yvonne', status: 'negative' },
{ id: '267', voterName: 'Zach', status: 'pending' },
{ id: '268', voterName: 'Ada', status: 'abstain' },
{ id: '269', voterName: 'Ben', status: 'affirmative' },
{ id: '270', voterName: 'Carla', status: 'negative' },
{ id: '271', voterName: 'Dan', status: 'pending' },
{ id: '272', voterName: 'Ella', status: 'abstain' },
{ id: '273', voterName: 'Fred', status: 'affirmative' },
{ id: '274', voterName: 'Grace', status: 'negative' },
{ id: '275', voterName: 'Harry', status: 'pending' },
{ id: '276', voterName: 'Irene', status: 'abstain' }];
</script>

<template>
  <VotePage :voteTotalCount="100" :votedCount="75" :affirmativeVoteCount="50" :negativeVoteCount="20"
    :abstainVoteCount="5" :voteItems="voteItems">
  </VotePage>
</template>

<style>
body {
  background-color: #1a1a1a;
}
</style>
